"""
dynamicDag
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
import pendulum

aaaa

default_args={
    "owner": "Vinod Sugur,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2024-01-30", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Vinod Sugur": "mailto:vinod.sugur@gmail.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/clrzw78t601ao01lvnktohcsf/cloud-ide/clrzw7vap004k01kccfjncojs/cls009t2p00t901mo6rp1ln2c",
    },
)
def dynamicDag():

dag_obj = dynamicDag()
